"use client";
import {useEffect,useState} from "react";
import {DashboardShell} from "@/components/dashboard-shell";
import {createClient} from "@/lib/supabase/client";
import {Plus,Search,Pencil,Trash2,X,Loader2,Users} from "lucide-react";
type Customer={id:string;name:string;email:string|null;phone:string|null;document:string|null;notes:string|null;created_at:string};
export default function Clientes(){
 const [rows,setRows]=useState<Customer[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[modal,setModal]=useState(false),[editing,setEditing]=useState<Customer|null>(null),[orgId,setOrgId]=useState<string|null>(null);
 const [name,setName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[document,setDocument]=useState(""),[notes,setNotes]=useState("");
 async function load(){const s=createClient();setLoading(true);setError("");const {data:{user}}=await s.auth.getUser();if(!user){setError("Sessão não encontrada.");setLoading(false);return}const {data:m,error:me}=await s.from("organization_members").select("organization_id").eq("user_id",user.id).limit(1).maybeSingle();if(me||!m){setError(me?.message||"Organização não encontrada.");setLoading(false);return}setOrgId(m.organization_id);const {data,error}=await s.from("customers").select("id,name,email,phone,document,notes,created_at").eq("organization_id",m.organization_id).order("created_at",{ascending:false});if(error)setError(error.message);else setRows(data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 function reset(){setEditing(null);setName("");setEmail("");setPhone("");setDocument("");setNotes("");setError("")}
 function edit(c:Customer){setEditing(c);setName(c.name);setEmail(c.email||"");setPhone(c.phone||"");setDocument(c.document||"");setNotes(c.notes||"");setModal(true)}
 async function save(e:React.FormEvent){e.preventDefault();if(!orgId||!name.trim())return setError("Informe o nome.");setSaving(true);setError("");const s=createClient();const payload={organization_id:orgId,name:name.trim(),email:email.trim()||null,phone:phone.trim()||null,document:document.trim()||null,notes:notes.trim()||null};const r=editing?await s.from("customers").update(payload).eq("id",editing.id):await s.from("customers").insert(payload);if(r.error)setError(r.error.message);else{setModal(false);reset();await load()}setSaving(false)}
 async function remove(id:string){if(!confirm("Excluir este cliente? As cobranças vinculadas também serão excluídas."))return;const s=createClient();const {error}=await s.from("customers").delete().eq("id",id);if(error)setError(error.message);else load()}
 const filtered=rows.filter(x=>[x.name,x.email||"",x.phone||"",x.document||""].join(" ").toLowerCase().includes(query.toLowerCase()));
 return <DashboardShell title="Clientes"><div className="space-y-6">
  <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h2 className="text-2xl font-black">Clientes</h2><p className="mt-1 text-sm text-slate-500">Cadastre e gerencie sua carteira real.</p></div><button onClick={()=>{reset();setModal(true)}} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white"><Plus size={18}/> Novo cliente</button></div>
  <div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-bold uppercase text-slate-400">Total de clientes</p><p className="mt-2 text-3xl font-black">{rows.length}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-bold uppercase text-slate-400">Resultado da busca</p><p className="mt-2 text-3xl font-black">{filtered.length}</p></div></div>
  <div className="flex items-center gap-3 rounded-2xl border bg-white px-4 py-3"><Search size={18} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nome, e-mail, WhatsApp ou documento..." className="w-full outline-none text-sm"/></div>
  {error&&<div className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}
  <div className="overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<div className="flex justify-center py-16"><Loader2 className="animate-spin text-blue-600"/></div>:filtered.length===0?<div className="py-16 text-center"><Users className="mx-auto text-slate-300"/><p className="mt-3 font-bold">Nenhum cliente encontrado</p><p className="mt-1 text-sm text-slate-500">Cadastre o primeiro cliente para começar.</p></div>:<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4">Cliente</th><th className="px-5 py-4">WhatsApp</th><th className="px-5 py-4">E-mail</th><th className="px-5 py-4">Cadastro</th><th className="px-5 py-4 text-right">Ações</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id} className="border-t"><td className="px-5 py-4 font-bold">{c.name}</td><td className="px-5 py-4">{c.phone||"—"}</td><td className="px-5 py-4">{c.email||"—"}</td><td className="px-5 py-4">{new Date(c.created_at).toLocaleDateString("pt-BR")}</td><td className="px-5 py-4 text-right"><button onClick={()=>edit(c)} className="mr-1 rounded-lg p-2 hover:bg-slate-100"><Pencil size={16}/></button><button onClick={()=>remove(c.id)} className="rounded-lg p-2 text-red-500 hover:bg-red-50"><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>}</div>
 </div>
 {modal&&<div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/50 p-4"><form onSubmit={save} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h3 className="text-xl font-black">{editing?"Editar cliente":"Novo cliente"}</h3><p className="text-sm text-slate-500">Os dados ficam vinculados à sua organização.</p></div><button type="button" onClick={()=>setModal(false)} className="rounded-xl p-2 hover:bg-slate-100"><X/></button></div><div className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-sm font-bold md:col-span-2">Nome<input required value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3" placeholder="Nome completo"/></label><label className="text-sm font-bold">WhatsApp<input value={phone} onChange={e=>setPhone(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3" placeholder="(75) 99999-9999"/></label><label className="text-sm font-bold">E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-bold">Documento<input value={document} onChange={e=>setDocument(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="text-sm font-bold md:col-span-2">Observações<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border px-4 py-3"/></label></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<button disabled={saving} className="mt-6 w-full rounded-xl bg-blue-600 py-3 font-bold text-white disabled:opacity-60">{saving?"Salvando...":editing?"Salvar alterações":"Cadastrar cliente"}</button></form></div>}
 </DashboardShell>
}