"use client";
import {useEffect,useMemo,useState} from "react";
import {ShieldCheck,Users,Building2,ReceiptText,WalletCards,RefreshCw,Search,Lightbulb,Crown} from "lucide-react";

const money=(v:number)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function AdminPage(){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("overview"),[search,setSearch]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/admin",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Acesso negado");setData(j)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function action(body:any){const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)alert(j.error||"Erro");else await load()}
 const orgs=useMemo(()=>data?.organizations?.filter((x:any)=>`${x.name} ${x.owner_email}`.toLowerCase().includes(search.toLowerCase()))||[],[data,search]);
 const users=useMemo(()=>data?.users?.filter((x:any)=>`${x.full_name} ${x.email}`.toLowerCase().includes(search.toLowerCase()))||[],[data,search]);
 if(loading)return <main className="min-h-screen grid place-items-center bg-slate-50"><RefreshCw className="animate-spin text-blue-600"/></main>;
 if(error)return <main className="min-h-screen grid place-items-center bg-slate-50 p-6"><div className="max-w-md rounded-3xl border bg-white p-8 text-center shadow-sm"><ShieldCheck className="mx-auto text-red-500" size={44}/><h1 className="mt-4 text-2xl font-black">Área restrita</h1><p className="mt-2 text-slate-500">{error}</p></div></main>;
 const s=data.stats;
 const nav=[["overview","Visão geral"],["organizations","Organizações"],["users","Usuários"],["subscriptions","Assinaturas"],["suggestions","Sugestões"]];
 return <main className="min-h-screen bg-slate-50 text-slate-950">
  <header className="sticky top-0 z-20 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-4 py-4 lg:px-8"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-cyan-500 text-white shadow-lg"><ShieldCheck/></div><div><p className="font-black">GestorPayOne Admin</p><p className="text-xs font-semibold text-slate-400">Painel administrativo central</p></div></div><div className="flex items-center gap-2"><span className="hidden text-sm font-bold text-slate-500 sm:block">{data.profile.email}</span><button onClick={load} className="rounded-xl border bg-white p-2.5 hover:bg-slate-50"><RefreshCw size={18}/></button></div></div></header>
  <div className="mx-auto grid max-w-[1500px] gap-6 px-4 py-6 lg:grid-cols-[220px_1fr] lg:px-8">
   <aside className="h-fit rounded-2xl border bg-white p-2 shadow-sm">{nav.map(([id,label])=><button key={id} onClick={()=>{setTab(id);setSearch("")}} className={"mb-1 w-full rounded-xl px-3 py-3 text-left text-sm font-bold "+(tab===id?"bg-blue-50 text-blue-700":"text-slate-600 hover:bg-slate-50")}>{label}</button>)}</aside>
   <section>
    {tab==="overview"&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[Building2,"Organizações",s.organizations],[Users,"Usuários",s.users],[ReceiptText,"Cobranças",s.charges],[WalletCards,"Recebido",money(s.revenue)]].map(([I,l,v]:any)=><div key={l} className="rounded-2xl border bg-white p-5 shadow-sm"><I className="text-blue-600"/><p className="mt-4 text-sm text-slate-500">{l}</p><p className="mt-1 text-2xl font-black">{v}</p></div>)}</div><div className="mt-5 grid gap-4 md:grid-cols-3">{[["Ativas",s.active,"text-emerald-600"],["Em teste",s.trial,"text-amber-600"],["Bloqueadas",s.blocked,"text-red-600"]].map(([l,v,c]:any)=><div key={l} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{l}</p><p className={"mt-1 text-2xl font-black "+c}>{v}</p></div>)}</div><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Em aberto</p><p className="mt-1 text-2xl font-black">{money(s.open)}</p></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Vencido</p><p className="mt-1 text-2xl font-black text-red-600">{money(s.overdue)}</p></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Assinaturas</p><p className="mt-1 text-2xl font-black">{s.subscriptions}</p></div></div></>}
    {tab==="organizations"&&<Panel title="Organizações"><SearchBox value={search} setValue={setSearch} placeholder="Buscar empresa ou e-mail"/><div className="space-y-3">{orgs.map((o:any)=><div key={o.id} className="rounded-2xl border p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><p className="font-black">{o.name}</p><p className="text-xs text-slate-500">{o.owner_email}</p><p className="mt-1 text-xs text-slate-400">Plano: {o.subscription_plan_code||"—"} · {new Date(o.created_at).toLocaleDateString("pt-BR")}</p></div><div className="flex flex-wrap gap-2">{["trial","active","blocked"].map((st:string)=><button key={st} onClick={()=>action({action:"organization_status",organization_id:o.id,status:st,target_type:"organization"})} className={"rounded-lg px-3 py-2 text-xs font-black "+(o.access_status===st?"bg-blue-600 text-white":"border bg-white text-slate-600")}>{st==="active"?"Ativar":st==="blocked"?"Bloquear":"Teste"}</button>)}</div></div></div>)}</div></Panel>}
    {tab==="users"&&<Panel title="Usuários"><SearchBox value={search} setValue={setSearch} placeholder="Buscar usuário"/><div className="space-y-3">{users.map((u:any)=><div key={u.id} className="flex flex-col justify-between gap-3 rounded-2xl border p-4 md:flex-row md:items-center"><div><div className="flex items-center gap-2"><p className="font-black">{u.full_name||"Sem nome"}</p>{u.is_admin&&<span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-black text-blue-700">ADMIN</span>}</div><p className="text-sm text-slate-500">{u.email}</p></div><button onClick={()=>action({action:"set_admin",user_id:u.id,is_admin:!u.is_admin,target_type:"user"})} className={"rounded-xl px-4 py-2 text-sm font-black "+(u.is_admin?"border bg-white text-red-600":"bg-blue-600 text-white")}>{u.is_admin?"Remover admin":"Tornar admin"}</button></div>)}</div></Panel>}
    {tab==="subscriptions"&&<Panel title="Assinaturas"><div className="space-y-3">{(data.subscriptions||[]).map((x:any)=><div key={x.id} className="flex flex-col justify-between gap-3 rounded-2xl border p-4 md:flex-row md:items-center"><div><p className="font-black">{x.plan_code}</p><p className="text-xs text-slate-500">Org: {x.organization_id}</p><p className="text-xs text-slate-400">Status: {x.status}</p></div><div className="flex gap-2"><button onClick={()=>action({action:"subscription_status",subscription_id:x.id,status:"active",target_type:"subscription"})} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white">Ativar</button><button onClick={()=>action({action:"subscription_status",subscription_id:x.id,status:"canceled",target_type:"subscription"})} className="rounded-xl border px-3 py-2 text-xs font-black text-red-600">Cancelar</button></div></div>)}</div></Panel>}
    {tab==="suggestions"&&<Panel title="Sugestões dos clientes"><div className="space-y-3">{(data.suggestions||[]).map((x:any)=><div key={x.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-black">{x.title}</p><p className="text-xs text-slate-500">{x.category} · {x.status}</p></div><Lightbulb className="text-amber-500"/></div><div className="mt-3 flex flex-wrap gap-2">{["reviewing","planned","completed","rejected"].map((st:string)=><button key={st} onClick={()=>action({action:"suggestion_status",suggestion_id:x.id,status:st,target_type:"suggestion"})} className="rounded-lg border px-3 py-2 text-xs font-bold">{st}</button>)}</div></div>)}</div></Panel>}
   </section>
  </div>
 </main>
}
function SearchBox({value,setValue,placeholder}:{value:string;setValue:(v:string)=>void;placeholder:string}){return <div className="mb-4 flex items-center gap-2 rounded-xl border px-3"><Search size={18} className="text-slate-400"/><input value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder} className="w-full bg-transparent py-3 outline-none"/></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><h1 className="text-xl font-black">{title}</h1><p className="text-sm text-slate-500">Gestão central do GestorPayOne</p></div><Crown className="text-blue-600"/></div>{children}</div>}
